churchtools:
  url: https://vg-sh.church.tools
  username: heizung@gemeinschaft-kaltenkirchen.de
  password: MKQ9cjt5aqf.zav-ruw
heating:
  cold: 0
  warm: 20
  earlystart: "01:00:00"
assignments:
  - tadozone: Saal
    earlystart: "04:00:00"
    resources:
      - KAKI großer Saal
  - tadozone: Saalbühne
    resources:
      - KAKI großer Saal
  - tadozone: Kleiner Saal
    earlystart: "02:30:00"
    resources:
      - KAKI kleiner Saal
  - tadozone: Küche
    warm: 19
    resources:
      - KAKI großer Saal
      - KAKI kleiner Saal
      - KAKI Küche
  - tadozone: Foyer
    warm: 19
    resources:
      - KAKI großer Saal
      - KAKI kleiner Saal
      - KAKI Küche
  - tadozone: WC Foyer
    resources:
      - KAKI großer Saal
      - KAKI kleiner Saal
      - KAKI Küche
  - tadozone: Kellertreppe
    warm: 15
    resources:
      - KAKI großer Saal
      - KAKI kleiner Saal
      - KAKI Küche
      - KAKI Kinderstunde (Keller)
      - KAKI Teenkreis (Keller)
  - tadozone: Kinderraum
    cold: 15
    resources:
      - KAKI Kinderstunde (Keller)
  - tadozone: Jugendraum
    cold: 15
    warm: 21
    earlystart: "02:00:00"
    resources:
      - KAKI Teenkreis (Keller)
tado:
  username: andreas.krutscher@vg-sh.de
  password: 4sjiny6y5KK3Erw
